Repository IN-CORE/incore-data-release, pull requests merged in 2022-02, with the labels that each got.

#8 dataset ids for econ loss analysis
  CHANGELOG.md
  released_dataset/README.md
Labels: enhancement

#7 5 release ids related to restoration
  CHANGELOG.md
  README.md
  released_fragility/README.md
  released_repair/README.md
  released_restoration/README.md
Labels: documentation

#10 Release/3.0.0
  CHANGELOG.md
  README.md
  datatypes/all.md
  datatypes/analyses_hazard_other.md
  released_dataset/README.md
  released_fragility/README.md
  released_repair/README.md
  released_restoration/README.md
Labels: release

#13 add Multi Objective Retrofit Optimization dataset ids and types
  CHANGELOG.md
  datatypes/all.md
  datatypes/dataservice_pull_down_menu.md
  released_dataset/README.md
Labels: enhancement
